### ISSUE TITLE
Failed to reproduce the PytorchModel examples

### ISSUE THREAD

**Issue by nychiang** [lanl-ansi/MathOptAI.jl#162]
It seems that the function PytorchModel is not implemented (see [here](https://github.com/lanl-ansi/MathOptAI.jl/blob/main/src/predictors/PytorchModel.jl)).
Are there plans to implement it? Or how we can reproduce the example?

@cnpetra

**Comment by odow** [comment]
Ah, the docs are missing the instruction
```julia
import PythonCall
```
The code is here:
https://github.com/lanl-ansi/MathOptAI.jl/blob/main/ext/MathOptAIPythonCallExt.jl

It gets loaded in the CI tests because I have
https://github.com/lanl-ansi/MathOptAI.jl/blob/42017ae346dac159e345a141a7357362a30efdf1/test/test_PythonCall.jl#L15
and it gets loaded in the documentation build because I have
https://github.com/lanl-ansi/MathOptAI.jl/blob/42017ae346dac159e345a141a7357362a30efdf1/docs/make.jl#L16

I need to clarify this in the docs. Or perhaps I should just add `PythonCall` as a strict dependency.

Thoughts @Robbybp? I initially wanted to keep the deps as light as possible, but it seems like PythonCall might be a pretty common use case (much more than say, Lux or Flux).

**Comment by odow** [comment]
I just made a PR to improve the documentation: https://github.com/lanl-ansi/MathOptAI.jl/pull/163

**Comment by Robbybp** [comment]
I say keep the dependencies light and clarify the docs

**Comment by odow** [comment]
Thanks for opening the issue @nychiang. Don't hesitate if you have other questions :smile:

**Comment by odow** [comment]
Release docs are now updated:
https://lanl-ansi.github.io/MathOptAI.jl/stable/api/#PytorchModel

![image](https://github.com/user-attachments/assets/fe4c264f-af97-47aa-adb4-75909b04c81a)

https://lanl-ansi.github.io/MathOptAI.jl/stable/tutorials/pytorch/

![image](https://github.com/user-attachments/assets/63d85fc9-4658-4ab4-b141-b4fa636f1842)
